### PR TITLE
Add header/footer mime type overrides to existing ContentTypes

### LINKED ISSUE #73: Missing override for header part
I was trying out `example/table` and Word isn't happy with the generated document. After running the document through https://github.com/mikeebowen/open-xml-validate, it looks like the issue is a missing override in `[Content Types].xml`. I see in `Package#add_header` that there is [an attempt](https://github.com/openxml/openxml-docx/blob/4e3111498465814870aaa6cc6a47e145d21d1a74/lib/openxml/docx/package.rb#L105) to add an override for the part, but it doesn't seem to be getting saved, so Word sees the part as having `application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml` as the MIME type instead of `application/vnd.openxmlformats-officedocument.wordprocessingml.document.header+xml`.

### PR DESCRIPTION
**Pull request by md5**
Fixes #73

### CODE REVIEW

**Comment by md5** [comment]
The CI failure is unrelated to my changes. Look like `simplecov-html` needs to either be pinned to a lower version for CI purposes or the CI needs to be updated to use Ruby 2.4. The EOL date for Ruby 2.3 was 2019-03-31, but I'm not sure if that matters one way or the other.

**Review by boblail — COMMENTED** [review]
The changes LGTM!

@kobsy, what versions of Ruby do you want in [.travis.yml](https://github.com/openxml/openxml-docx/blob/master/.travis.yml#L4)? (Would you rather use GitHub Actions?)

**Comment by kobsy** [comment]
My apologies, @md5! I somehow missed the GitHub notifications for this PR, so it fell through the cracks. 🙇 I just circled back around and switched the project over from using Travis to using GitHub Actions. I think if you rebase on the latest `master`, that should fix the CI failures. I agree with Bob that the changes themselves look good. 👍 Thanks! 😁

**Comment by md5** [comment]
@kobsy done!

**Pull request merged**
