### PR TITLE
Added transitional attributes for ind and tblLook

### PR DESCRIPTION
**Pull request by kobsy**

### CODE REVIEW

**Comment by boblail** [comment]
The code looks fine. What's this for? What's a transitional attribute?

**Comment by kobsy** [comment]
I think they're elements that Microsoft started using when they made the switch to `docx`, but ended up dropping once they updated the spec in 2010 or so. So while they're not officially in the spec, they're more widely used and understood by 3rd party word processors like Pages & Google Docs, as well as still being understood and supported by Word, even if it prefers what's in the official spec.

**Comment by boblail** [comment]
Oh, interesting!

Would it make sense to document that these are unofficial features? Like:

```ruby
  # Microsoft started using these elements in 2007, but they were dropped from
  # the spec in 2010. Despite being unofficial, they're more widely used by 3rd party
  # word processors like Pages and Google Docs.
  attribute :left, expects: :integer
  attribute :left_characters, expects: :integer, displays_as: :leftChars
  attribute :right, expects: :integer
  attribute :right_characters, expects: :integer, displays_as: :rightChars
```

or

```ruby
  attribute :left, expects: :integer, version: 2007
  attribute :left_characters, expects: :integer, displays_as: :leftChars, version: 2007
  attribute :right, expects: :integer, version: 2007
  attribute :right_characters, expects: :integer, displays_as: :rightChars, version: 2007
```

or

```ruby
  attribute :left, expects: :integer, deprecated: true
  attribute :left_characters, expects: :integer, displays_as: :leftChars, deprecated: true
  attribute :right, expects: :integer, deprecated: true
  attribute :right_characters, expects: :integer, displays_as: :rightChars, deprecated: true
```

**Comment by boblail** [comment]
Does this actually belong in a separate commit? It looks like a correction.
```diff
-          attribute :first_line, expects: :integer
+          attribute :first_line, expects: :integer, displays_as: :firstLine
```

**Comment by kobsy** [comment]
I looked up the introduction for the transitional spec, and it described the transitional elements as being intended to "enable a transitional period during which existing binary documents being migrated to ECMA-376 can make use of legacy features to preserve their fidelity, while noting that new documents should not use them." So I decided to go with the `deprecated: true`, as I think it's maybe the best description of what's going on with these transitional elements.

I also moved the fix to its own commit.

**Comment by boblail** [comment]
:+1:

**Pull request merged**
