### PR TITLE
Font embedding

### PR DESCRIPTION
**Pull request by kobsy**
Added ability to embed fonts (but only works on Windows) :disappointed:

### CODE REVIEW

**Comment by boblail** [comment]
Are some of these features (like adding `"fontTable.xml"` to the Package and defining `elements/fonts/family.rb`) things that `OpenXml::Docx` should implement whether or not it supports font embedding? (Should they be in a separate commit?)

**Comment by boblail** [comment]
It looks like you're also toying with a different convention for organizing source files in this PR (adding the `fonts` folder underneath `elements`).

Let's discuss that apart from Font Embedding too.

 1. Do you think we should group elements (and properties) by feature? How would that help? What would it solve?
 2. The path `openxml/docx/elements/fonts/embedBoldItalic.rb` now defines `OpenXml::Docx::Elements::EmbedBoldItalic` — which is slightly surprising. There's a strong Ruby convention of mapping paths to namespaces that would lead you to expect the class to be `OpenXml::Docx::Elements::Fonts::EmbedBoldItalic`. Should we break convention? Or group elements this way and deepen the namespaces as well?

(For my 2¢, I'm not bothered overmuch by the large number of files under `elements` and `properties` and would be disinclined to add one more module to elements' and properties' namespaces.)

**Comment by kobsy** [comment]
@boblail, I went ahead and moved the font elements into the root elements folder. As you say, doing it the other way broke convention.

**Comment by kobsy** [comment]
I also broke the Font Table changes into their own commit.

**Comment by boblail** [comment]
@kobsy, should 7257f28 be squashed onto 29a720e?

**Comment by kobsy** [comment]
@boblail Probably

**Comment by boblail** [comment]
@kobsy Alright, I'll do it when I merge this.

**Pull request merged**
