### PR TITLE
Suggested file restructuring

### PR DESCRIPTION
**Pull request by cacqw7**
I nested any **Properties** or **Elements** that started with the same `prefix_` into subfolders.

### CODE REVIEW

**Comment by boblail** [comment]
Chase, can you talk about this refactor? How does it help? What does it solve?

**Comment by cacqw7** [comment]
As we were adding more `Properties` and `Elements`, the folders were getting pretty large and difficult to scan quickly to find what you were looking for. This was just a way to consolidate similarly named files into subfolders. 

I can take or leave this refactor. On the one hand, it makes it a little easier to traverse the file tree, but I can also see this structure being difficult to maintain since sorts by filenames rather than the spec.

**Comment by boblail** [comment]
Check out this discussion: https://github.com/openxml/openxml-docx/pull/33#issuecomment-164316604 — it's related.

I'm leaning toward closing this PR.

**Comment by cacqw7** [comment]
@boblail I agree. I think it's best if we close this PR.

**Pull request closed without merging**
