### PR TITLE
Add Hyperlink element

### PR DESCRIPTION
**Pull request by mvz**
The hyperlink element was missing. This pull request adds it.

### CODE REVIEW

**Review by boblail — APPROVED** [review]
LGTM!

(Section 17.16.22 in the spec)

**Comment by mvz** [comment]
Hi! Anything I can do to help get this merged and released?

**Comment by kobsy** [comment]
Sorry for the delay on this; the PR had flown under my radar. 😓 The addition and tests look great, though! Thanks for the PR! 😁

**Comment by mvz** [comment]
Hi @kobsy no problem, these things happen. Thanks for taking care of this!

**Pull request merged**
